"""项目路径与全局数值配置。"""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
ATTACHMENT_DIR = DATA_DIR
RESULT_DIR = PROJECT_ROOT / "result"
TEMPLATE_DIR = RESULT_DIR
FIGURE_DIR = PROJECT_ROOT / "report" / "figures"

INITIAL_T_K = 28.0 + 273.15
INITIAL_C = 2.55
INITIAL_RADIUS_M = 0.02
PLATEAU_START_S = 7200.0
RADIUS_MAX_TIME_S = 72.0 * 3600.0
FIXED_COMPARISON_MAX_TIME_S = 10.0 * 24.0 * 3600.0
POST_DRY_S = 1800.0

HEAT_TRANSFER_DEFAULT = 25.0
MASS_TRANSFER_DEFAULT = 8.0e-7
DIFFUSIVITY_SCALE_DEFAULT = 1.0

